// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGdVIPlIEXZN6t7NiqRIgxQxpFCSQcOfY',
    appId: '1:714880210172:web:2cd98113c395619a86b379',
    messagingSenderId: '714880210172',
    projectId: 'leoni-moreira',
    authDomain: 'leoni-moreira.firebaseapp.com',
    storageBucket: 'leoni-moreira.firebasestorage.app',
    measurementId: 'G-TNCQDDWYL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn0FF2-17hxnvDTGaQscru2su-u9gGmkQ',
    appId: '1:714880210172:android:af00f265945f058186b379',
    messagingSenderId: '714880210172',
    projectId: 'leoni-moreira',
    storageBucket: 'leoni-moreira.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8fcPywUCb11EgH9ay6vrFrWh_6XHxMN4',
    appId: '1:714880210172:ios:ad16a4d39bc0c23186b379',
    messagingSenderId: '714880210172',
    projectId: 'leoni-moreira',
    storageBucket: 'leoni-moreira.firebasestorage.app',
    iosBundleId: 'LeoNino.com.leoniMm',
  );

}